### ISSUE TITLE
[personal-blog] layout the blog-post page UI

### ISSUE THREAD

**Issue by bryanlundberg** [ivaniuss/collaborative-projects#11]
Here: [PostPage.tsx](https://github.com/ivaniuss/collaborative-projects/blob/main/personal-blog/client-react/src/pages/PostPage.tsx)

**Comment by ivaniuss** [comment]
Isn't it the same as the issue #7 ?

**Comment by bryanlundberg** [comment]
I'm not sure if you're making the home page or the post page.

**Comment by Tron89** [comment]
The post page :D

**Comment by Tron89** [comment]
The post page

**Comment by ivaniuss** [comment]
okay. Let's work on the other issue then
