### ISSUE TITLE
[personal-blog] Define and implement backend

### ISSUE THREAD

**Issue by bryanlundberg** [ivaniuss/collaborative-projects#9]
This task should address the following:

- Basic backend architecture
- MongoDB connection
- Blog post schema

**Comment by ivaniuss** [comment]
which technology are you going to use?. I have already done one in Nestjs that is in develop

**Comment by bryanlundberg** [comment]
It wasn't for me, I was adding it to the activities to do, all yours then. 😅

**Comment by ivaniuss** [comment]
oh. Got it hehe thanks then!
